package uk.ac.ebi.pride.mongodb.molecules.model.protein;

import org.junit.Test;
import uk.ac.ebi.pride.archive.dataprovider.data.ptm.DefaultIdentifiedModification;
import uk.ac.ebi.pride.archive.dataprovider.param.DefaultCvParam;
import uk.ac.ebi.pride.mongodb.archive.model.param.MongoCvParam;

import java.util.Collections;

public class PrideMongoProteinEvidenceTest {

    @Test
    public void builder() {

        PrideMongoProteinEvidence protein = PrideMongoProteinEvidence.builder()
                .reportedAccession("sp|Q672I1|POLG_SVSAP")
                .projectAccession("PXD000433")
                .proteinSequence("MVSKPFKPIVLNATFEWQVFKRCYLRVAPREAFCENLSELHHYFARRVNAWLKHATRTLP\n" +
                        "DGYTFVEEGLLDMFGTKAPDSVQEGTLFRELFGVDQTEQFPLSLADLAKLQGELVDATRT\n" +
                        "PGHALRQKYTMTTIQDLINKITKVVPVQATLTEMHARRQFERERADLFHELPLVDEDAVS\n" +
                        "QPKTYFYTMWRQVVKKGKAYFCPLVKTSAWRTKISAITEPIKDFLIAFCQAVQQEMGVNP\n" +
                        "QYLQLAWLQKLKPTTLTIILQQHKYTVSGWLATMTALVEVYSNLFDDLRKSSVAIVSSIG\n" +
                        "AFFDICKDFVSQVVELVKTTFTAQGPTDLGWAAVLAGAAMILLKMSGCPGVIGMWTKVLK\n" +
                        "ICGGITTITAAARGVRWLKDLYEEAEGRRLAKMYMARGAALIELAASREVTGIDELKGLL\n" +
                        "DCFTILIEEGTELIHKFGTSPLAGLVRTYVSELETQANNIRSTIKLDTPRRVPVVIILTG\n" +
                        "APGIGKTRLAQYVGQRFGKTSNFSVAVDHHDGYTGNTVCIWDEFDVDSKGAFVETMIGIA\n" +
                        "NTAPFPLNCDRVENKGRVFTSDYVICTSNYPTSVIPDNPRAAAFYRRVLTVDVSAPDLEE\n" +
                        "WKKRNPGKRPTPDLYQDDFSHLKLMLRPYLGYNPDGDTLEGPRVAPTQISIAGLITLMER\n" +
                        "RFKEQAGPLQNLWLQVPKTLVEQSTNMVKAFMYANRAVCDVIPNPATRDIAETALTKIFV\n" +
                        "CGTAPPPEFVGKHIVITGIEVGDASIANSLLSMFTTTTRLSAAAQREYMYRVWSPLIHIQ\n" +
                        "DRSINTQNLPYINRVIPVTSHWDFLRGLRHHLGFTSIPGMWKAFQGWRTSQGIVDFVAHH\n" +
                        "MADVTFPSNPECTIFRTPDADVVFYTFGSYVCFATPARVPYVGTPPTTIHSNTPRCMTWG\n" +
                        "ETIALLCEVVAEFVLHFGPVILSAANIAYLMTRGSRTEEAKGKTKHGRGMRHGHRAGVSL\n" +
                        "SDDEYDEWRDLMRDWRRDMSVNDFLMLRERSALGVDDEDEARYRAWLEIRAMRMAGGAYT\n" +
                        "HATIIGRGGVRDEIIRTAPRRAPTRPQQHYEEEAPTAIVEFTQGGDHIGYGVHIGNGNVI\n" +
                        "TVTHVASTSDEVNGSAFKITRTVGETTWVQGPFSQLPHMQIGSGSPVYFTTRLHPVFTIS\n" +
                        "EGTFETPNITVNGFHVRIMNGYPTKKGDCGLPYFNSNRQLVALHAGTDTQGETKVAQRVV\n" +
                        "KEVTTQDEFQWKGLPVVKSGLDVGGMPTGTRYHRSPAWPEEQPGETHAPAPFGAGDKRYT\n" +
                        "FSQTEMLVNGLKPYTEPTAGVPPQLLSRAVTHVRSYIETIIGTHRSPVLTYHQACELLER\n" +
                        "TTSCGPFVQGLKGDYWDEEQQQYTGVLANHLEQAWDKANKGIAPRNAYKLALKDELRPIE\n" +
                        "KNKAGKRRLLWGCDAATTLIATAAFKAVATRLQVVTPMTPVAVGINMDSVQMQVMNDSLK\n" +
                        "GGVLYCLDYSKWDSTQNPAVTAASLAILERFAEPHPIVSCAIEALSSPAEGYVNDIKFVT\n" +
                        "RGGLPSGMPFTSVVNSINHMIYVAAAILQAYESHNVPYTGNVFQVETVHTYGDDCMYSVC\n" +
                        "PATASIFHAVLANLTSYGLKPTAADKSDAIKPTNTPVFLKRTFTQTPHGVRALLDITSIT\n" +
                        "RQFYWLKANRTSDPSSPPAFDRQARSAQLENALAYASQHGPVVFDTVRQIAIKTAQGEGL\n" +
                        "VLVNTNYDQALATYNAWFIGGTVPDPVGHTEGTHKIVFEMEGNGSNPEPKQSNNPMVVDP\n" +
                        "PGTTGPTTSHVVVANPEQPNGAAQRLELAVATGAIQSNVPEAIRNCFAVFRTFAWNDRMP\n" +
                        "TGTFLGSISLHPNINPYTAHLSGMWAGWGGSFEVRLSISGSGVFAGRIIASVIPPGVDPS\n" +
                        "SIRDPGVLPHAFVDARITEPVSFMIPDVRAVDYHRMDGAEPTCSLGFWVYQPLLNPFSTT\n" +
                        "AVSTCWVSVETKPGGDFDFCLLRPPGQQMENGVSPEGLLPRRLGYSRGNRVGGLVVGMVL\n" +
                        "VAEHKQVNRHFNSNSVTFGWSTAPVNPMAAEIVTNQAHSTSRHAWLSIGAQNKGPLFPGI\n" +
                        "PNHFPDSCASTIVGAMDTSLGGRPSTGVCGPAISFQNNGDVYENDTPSVMFATYDPLTSG\n" +
                        "TGVALTNSINPASLALVRISNNDFDTSGFANDKNVVVQMSWEMYTGTNQIRGQVTPMSGT\n" +
                        "NYTFTSTGANTLVLWQERMLSYDGHQAILYSSQLERTAEYFQNDIVNIPENSMAVFNVET\n" +
                        "NSASFQIGIRPDGYMVTGGSIGINVPLEPETRFQYVGILPLSAALSGPSGNMGRARRVFQ")
                .proteinDescription("Genome polyprotein OS=Sapporo virus (isolate GI/Human/Germany/pJG-Sap01) OX=291175 PE=3 SV=1")
                .proteinGroupMembers(Collections.singleton("sp|Q672I1|POLG_SVSAP"))
                .isDecoy(true)
                .build();

        protein.addAttribute(new MongoCvParam("MS", "MS:1001013", "database name", "phytophtora_infestans_rnd"));
        protein.addAttribute(new MongoCvParam("MS", "MS:1001016", "database version", "20100422.fasta"));

        DefaultIdentifiedModification mod = new DefaultIdentifiedModification(new DefaultCvParam("UNIMOD", "UNIMOD:35", "Oxidation", "15.994915"), null, null, null);
        protein.addIdentifiedModification(mod);

        System.out.println(protein.toString());

    }
}